'use strict';

const app = document.getElementById('app');
const nav = document.getElementById('nav');
const mobileMenu = document.getElementById('mobile-menu');
const dataStatus = document.getElementById('data-status');
const lastUpdate = document.getElementById('last-update');
const statusDot = document.querySelector('.status-dot');

const state = {
  aircraft: [], aircraftUpdatedAt: null, aircraftSource: 'connecting', selectedAircraft: null,
  reportStep: 1, draft: freshDraft(), issuedReport: null,
  pilotCase: null, pilotStage: 'lookup', publicReports: [], sheetsConfigured: null
};

const DEMO_REPORTS = [
  {id:'PPD-2026-0811-0018',callsign:'Jetstar-441',aircraftType:'Airbus A320',incidentType:'Heading Deviation',location:'IRFD',date:'11 AUG 2026',status:'Closed',disposition:'Dismissed',summary:'Reported heading deviation reviewed and dismissed after pilot response and available evidence.'},
  {id:'PPD-2026-0808-0012',callsign:'Cargo-218',aircraftType:'Boeing 767F',incidentType:'Runway Incursion',location:'IPPH',date:'08 AUG 2026',status:'Under Review',disposition:'Pending',summary:'Community case awaiting review. Demo record only.'},
  {id:'PPD-2026-0803-0007',callsign:'Shamrock-502',aircraftType:'Boeing 787-9',incidentType:'Altitude Deviation',location:'IZOL CTR',date:'03 AUG 2026',status:'Closed',disposition:'Confirmed',summary:'Altitude deviation confirmed within the scope of the ATC24 community review process.'}
];

function freshDraft(){return {aircraft:{callsign:'',playerName:'',aircraftType:'',source:'manual'},incident:{category:'Altitude Deviation',airport:'',airspace:'',controllerPosition:'TWR',occurredAt:new Date().toISOString(),assignedAltitude:'',observedAltitude:'',assignedHeading:'',observedHeading:'',assignedRunway:'',observedRunway:''},atcReport:{atcUsername:'',instruction:'',observedAction:'',narrative:'',evidenceUrl:''}}}
function esc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function normalizeNumber(v){const d=String(v||'').replace(/\D/g,'');return d.length===6?d:''}
function fmtAltitude(v){const n=Number(v)||0;return `${Math.round(n).toLocaleString()} FT`}
function fmtTime(iso){const d=new Date(iso);if(Number.isNaN(d.getTime()))return '—';return `${String(d.getUTCDate()).padStart(2,'0')} ${d.toLocaleString('en',{month:'short',timeZone:'UTC'}).toUpperCase()} ${d.getUTCFullYear()} / ${String(d.getUTCHours()).padStart(2,'0')}${String(d.getUTCMinutes()).padStart(2,'0')}Z`}
function incidentLabel(v){return String(v||'Other').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function route(){return (location.hash.replace('#','')||'home').split('?')[0]}
function setRoute(r){location.hash=r}
function toast(message){const el=document.createElement('div');el.className='toast';el.textContent=message;document.getElementById('toast-region').appendChild(el);setTimeout(()=>el.remove(),3400)}
function statusClass(status){const s=String(status||'').toLowerCase();if(s.includes('dismiss'))return'dismissed';if(s.includes('confirm'))return'confirmed';if(s.includes('respond'))return'responded';if(s.includes('review')||s.includes('await'))return'awaiting';if(s.includes('live')||s.includes('closed'))return'live';return'info'}
function localReports(){try{return JSON.parse(localStorage.getItem('24pd_reports')||'[]')}catch{return[]}}
function saveLocalReports(items){localStorage.setItem('24pd_reports',JSON.stringify(items))}
function localCreate(draft){const reports=localReports();let ppd='';do{ppd=String(Math.floor(100000+Math.random()*900000))}while(reports.some(r=>r.ppdNumber===ppd));const now=new Date();const id=`PPD-${now.getUTCFullYear()}-${String(now.getUTCMonth()+1).padStart(2,'0')}${String(now.getUTCDate()).padStart(2,'0')}-${String(reports.length+1).padStart(4,'0')}`;const report={id,ppdNumber:ppd,status:'Awaiting Pilot Response',...structuredClone(draft),createdAt:now.toISOString(),demoLocal:true};reports.push(report);saveLocalReports(reports);return report}
function localLookup(number){return localReports().find(r=>r.ppdNumber===number)||null}
function localRespond(caseId,response){const reports=localReports();const i=reports.findIndex(r=>r.id===caseId);if(i<0)return false;reports[i].pilotResponse=response;reports[i].status='Pilot Responded';reports[i].updatedAt=new Date().toISOString();saveLocalReports(reports);return true}

async function api(url, options={}){const res=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let body={};try{body=await res.json()}catch{}if(!res.ok){const error=new Error(body.error||`HTTP ${res.status}`);error.status=res.status;error.body=body;throw error}return body}

async function checkHealth(){try{const h=await api('/api/health');state.sheetsConfigured=h.sheetsConfigured}catch{state.sheetsConfigured=false}}
async function refreshAircraft(){try{const body=await api('/api/aircraft');state.aircraft=body.aircraft||[];state.aircraftUpdatedAt=body.updatedAt;state.aircraftSource=body.source;setDataStatus(body.source==='mock'?'MOCK DATA':'24DATA LIVE','live',body.stale?'stale':`updated ${relative(body.updatedAt)}`)}catch{state.aircraft=[];state.aircraftSource='offline';setDataStatus('OFFLINE','offline','manual entry available')}if(route()==='aircraft')renderAircraft()}
function setDataStatus(text,kind,sub){dataStatus.textContent=text;lastUpdate.textContent=sub;statusDot.className=`status-dot ${kind}`}
function relative(iso){const sec=Math.max(0,Math.round((Date.now()-new Date(iso).getTime())/1000));return sec<2?'now':`${sec}s ago`}

function shellBanner(){if(state.sheetsConfigured===false)return `<div class="data-banner"><span><strong>DEMO STORAGE:</strong> Google Sheets is not configured yet. Reports created on this device will use local browser storage.</span><span class="mono">LOCAL FALLBACK</span></div>`;return''}
function render(){const r=route();document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===r));nav.classList.remove('open');mobileMenu.setAttribute('aria-expanded','false');if(r==='aircraft')renderAircraft();else if(r==='file')renderFile();else if(r==='respond')renderRespond();else if(r==='reports')renderReports();else renderHome();window.scrollTo({top:0,behavior:'instant'});app.focus({preventScroll:true})}

function renderHome(){app.innerHTML=`${shellBanner()}<section class="hero"><div class="hero-copy"><div class="eyebrow">ATC24 community reporting</div><h1>Clear reports.<br>Fair responses.</h1><p>Document a possible pilot deviation, issue a six-digit contact number, and give the involved pilot a structured way to respond — built around the way ATC24 actually operates.</p><div class="hero-meta"><div><strong>6 DIGITS</strong>spoken PPD number</div><div><strong>UTC</strong>incident timestamps</div><div><strong>24DATA</strong>live aircraft feed</div></div></div><div class="radar-card" aria-hidden="true"><div class="radar-grid"></div><div class="radar-rings"></div><div class="sweep"></div><div class="radar-copy"><strong>POSSIBLE PILOT DEVIATION</strong><p>“Advise when ready to copy a number.”<br>Community workflow, adapted for ATC24.</p></div></div></section><section class="workflow-grid"><article class="action-card"><div class="kicker">Controller / ATC</div><h2>File a Possible Pilot Deviation</h2><p>Select an aircraft from the current ATC24 feed or enter it manually, document the event, then issue a PPD number to the pilot.</p><button class="btn primary" id="home-file">FILE PPD</button></article><article class="action-card"><div class="kicker">Pilot response</div><h2>Were you given a number?</h2><p>Enter the six-digit PPD number provided by ATC. Hyphens and the 24PD prefix are accepted.</p><div class="lookup-box"><input id="home-number" inputmode="numeric" maxlength="12" placeholder="24PD-482731" aria-label="PPD number"><button class="btn primary" id="home-lookup">LOCATE REPORT</button></div></article></section>`;document.getElementById('home-file').onclick=()=>setRoute('file');document.getElementById('home-lookup').onclick=()=>{const v=document.getElementById('home-number').value;sessionStorage.setItem('24pd_lookup',v);setRoute('respond')};document.getElementById('home-number').addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('home-lookup').click()})}

function renderAircraft(){const rows=state.aircraft;app.innerHTML=`${shellBanner()}<div class="section-head"><div><div class="eyebrow">Live operations</div><h1>ATC24 Aircraft</h1><p>${rows.length?`${rows.length} aircraft received from ${esc(state.aircraftSource)}.`:'Live feed unavailable — manual report entry remains available.'}</p></div><div class="section-actions"><button class="btn" id="refresh-aircraft">REFRESH</button><button class="btn primary" id="manual-file">MANUAL REPORT</button></div></div><div class="filter-bar"><input id="air-search" placeholder="Search callsign or pilot"><select id="air-type"><option value="">All aircraft types</option>${[...new Set(rows.map(a=>a.aircraftType))].sort().map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="air-status"><option value="">All statuses</option><option value="airborne">Airborne</option><option value="ground">Ground</option><option value="emergency">Emergency</option></select><div class="subtle mono" style="align-self:center;text-align:right">${state.aircraftUpdatedAt?relative(state.aircraftUpdatedAt):'—'}</div></div><div class="table-shell"><table><thead><tr><th>Callsign</th><th>Pilot</th><th>Aircraft</th><th>Altitude</th><th>Heading</th><th>Speed</th><th>Status</th><th></th></tr></thead><tbody id="air-body"></tbody></table></div>`;const renderRows=()=>{const q=document.getElementById('air-search').value.toLowerCase(),type=document.getElementById('air-type').value,status=document.getElementById('air-status').value;const filtered=rows.filter(a=>(!q||a.callsign.toLowerCase().includes(q)||a.playerName.toLowerCase().includes(q))&&(!type||a.aircraftType===type)&&(!status||(status==='emergency'?a.isEmergencyOccuring:status==='ground'?a.isOnGround:!a.isOnGround)));document.getElementById('air-body').innerHTML=filtered.length?filtered.map(a=>`<tr><td class="callsign">${esc(a.callsign)}</td><td>${esc(a.playerName)}</td><td>${esc(a.aircraftType)}</td><td class="mono">${fmtAltitude(a.altitude)}</td><td class="mono">${Math.round(a.heading)}°</td><td class="mono">${Math.round(a.speed)} KT</td><td><span class="status-badge ${a.isEmergencyOccuring?'danger':a.isOnGround?'warn':'live'}">${a.isEmergencyOccuring?'Emergency':a.isOnGround?'Ground':'Airborne'}</span></td><td><button class="btn ghost view-aircraft" data-i="${rows.indexOf(a)}">VIEW</button></td></tr>`).join(''):`<tr><td colspan="8"><div class="empty-state"><strong>No matching aircraft</strong>Adjust the filters or file a manual report.</div></td></tr>`;document.querySelectorAll('.view-aircraft').forEach(b=>b.onclick=()=>openAircraft(rows[Number(b.dataset.i)]))};['air-search','air-type','air-status'].forEach(id=>document.getElementById(id).addEventListener('input',renderRows));renderRows();document.getElementById('refresh-aircraft').onclick=refreshAircraft;document.getElementById('manual-file').onclick=()=>{state.selectedAircraft=null;state.draft=freshDraft();state.reportStep=1;setRoute('file')}}

function openAircraft(a){state.selectedAircraft=a;const back=document.createElement('div');back.className='drawer-backdrop';const drawer=document.createElement('aside');drawer.className='drawer';drawer.innerHTML=`<div class="drawer-head"><span class="eyebrow">Aircraft detail</span><button class="icon-btn" aria-label="Close">×</button></div><div class="aircraft-title">${esc(a.callsign)}</div><div class="subtle">${esc(a.aircraftType)} · ${a.isEmergencyOccuring?'EMERGENCY':a.isOnGround?'GROUND':'AIRBORNE'}</div><div class="metric-grid"><div class="metric"><span>PILOT</span><strong style="font-size:13px">${esc(a.playerName)}</strong></div><div class="metric"><span>ALTITUDE</span><strong>${Math.round(a.altitude).toLocaleString()}</strong></div><div class="metric"><span>HEADING</span><strong>${Math.round(a.heading)}°</strong></div><div class="metric"><span>AIRSPEED</span><strong>${Math.round(a.speed)} KT</strong></div><div class="metric"><span>GROUND SPEED</span><strong>${Math.round(a.groundSpeed)} KT</strong></div><div class="metric"><span>STATUS</span><strong style="font-size:13px">${a.isEmergencyOccuring?'EMERGENCY':a.isOnGround?'GROUND':'NORMAL'}</strong></div></div><div class="callout ${a.isEmergencyOccuring?'warn':''}">${a.isEmergencyOccuring?'24Data indicates an emergency is active. An emergency is not itself evidence of a deviation.':'Live values are context only and are not continuously stored by 24Pilot Deviation.'}</div><div class="button-row" style="margin-top:18px"><button class="btn primary" id="drawer-file">FILE POSSIBLE PILOT DEVIATION</button></div>`;const close=()=>{back.remove();drawer.remove()};back.onclick=close;drawer.querySelector('.icon-btn').onclick=close;drawer.querySelector('#drawer-file').onclick=()=>{state.draft=freshDraft();state.draft.aircraft={callsign:a.callsign,playerName:a.playerName,aircraftType:a.aircraftType,source:'24data'};state.reportStep=1;close();setRoute('file')};document.body.append(back,drawer)}

function renderFile(){const labels=['Aircraft','Incident','Details','Review'];app.innerHTML=`${shellBanner()}<div class="section-head"><div><div class="eyebrow">Controller workflow</div><h1>File Possible Pilot Deviation</h1><p>Keep the report factual, chronological, and limited to the ATC24 event.</p></div><div class="status-badge info">STEP ${state.reportStep} / 4</div></div><div class="stepper">${labels.map((_,i)=>`<div class="step ${i<state.reportStep?'active':''}"></div>`).join('')}</div><div id="file-stage"></div>`;renderFileStage()}
function renderFileStage(){const host=document.getElementById('file-stage');const d=state.draft;if(state.reportStep===1){host.innerHTML=`<div class="form-section"><h3>Aircraft involved</h3><div class="form-grid"><div class="field"><label>Callsign *</label><input id="f-callsign" value="${esc(d.aircraft.callsign)}" placeholder="Shamrock-1337"></div><div class="field"><label>Roblox username</label><input id="f-pilot" value="${esc(d.aircraft.playerName)}" placeholder="Pilot username"></div><div class="field full"><label>PTFS aircraft *</label><input id="f-type" value="${esc(d.aircraft.aircraftType)}" placeholder="Airbus A330"></div></div>${d.aircraft.source==='24data'?'<div class="callout" style="margin-top:15px">LIVE DATA — Callsign, pilot, and aircraft were copied from the current 24Data feed.</div>':''}</div><div class="button-row"><button class="btn" id="choose-live">CHOOSE LIVE AIRCRAFT</button><button class="btn primary" id="next">CONTINUE</button></div>`;document.getElementById('choose-live').onclick=()=>setRoute('aircraft');document.getElementById('next').onclick=()=>{d.aircraft.callsign=document.getElementById('f-callsign').value.trim();d.aircraft.playerName=document.getElementById('f-pilot').value.trim();d.aircraft.aircraftType=document.getElementById('f-type').value.trim();if(!d.aircraft.callsign||!d.aircraft.aircraftType)return toast('Callsign and aircraft type are required.');state.reportStep=2;renderFile()}}
else if(state.reportStep===2){host.innerHTML=`<div class="form-section"><h3>Incident classification</h3><div class="form-grid"><div class="field"><label>Incident type *</label><select id="f-category">${['Altitude Deviation','Heading Deviation','Route Deviation','Runway Incursion','Unauthorized Takeoff','Unauthorized Landing','Failure to Follow ATC Instruction','Missed / Incorrect Handoff','Airspace Violation','Separation Issue','Speed Deviation','Taxi Instruction Deviation','Other'].map(x=>`<option ${d.incident.category===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Controller position</label><select id="f-position">${['DEL','GND','TWR','APP','DEP','CTR','OTHER'].map(x=>`<option ${d.incident.controllerPosition===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Airport</label><input id="f-airport" value="${esc(d.incident.airport)}" placeholder="IRFD"></div><div class="field"><label>Airspace / ACC</label><input id="f-airspace" value="${esc(d.incident.airspace)}" placeholder="IZOL CTR"></div><div class="field"><label>ATC Roblox username</label><input id="f-atc" value="${esc(d.atcReport.atcUsername)}" placeholder="Controller username"></div><div class="field"><label>Occurred at</label><input id="f-time" type="datetime-local" value="${toLocalInput(d.incident.occurredAt)}"><small>Stored and displayed in UTC/Zulu after submission.</small></div></div></div><div class="button-row"><button class="btn" id="back">BACK</button><button class="btn primary" id="next">CONTINUE</button></div>`;document.getElementById('back').onclick=()=>{state.reportStep=1;renderFile()};document.getElementById('next').onclick=()=>{d.incident.category=document.getElementById('f-category').value;d.incident.controllerPosition=document.getElementById('f-position').value;d.incident.airport=document.getElementById('f-airport').value.trim();d.incident.airspace=document.getElementById('f-airspace').value.trim();d.atcReport.atcUsername=document.getElementById('f-atc').value.trim();d.incident.occurredAt=new Date(document.getElementById('f-time').value||Date.now()).toISOString();state.reportStep=3;renderFile()}}
else if(state.reportStep===3){host.innerHTML=`<div class="form-section"><h3>Reported event</h3><div class="form-grid">${dynamicFields(d)}<div class="field full"><label>ATC instruction / clearance *</label><textarea id="f-instruction" placeholder="Climb and maintain 5,000 feet.">${esc(d.atcReport.instruction)}</textarea></div><div class="field full"><label>Observed aircraft action *</label><textarea id="f-action" placeholder="Aircraft continued climbing through 6,200 feet.">${esc(d.atcReport.observedAction)}</textarea></div><div class="field full"><label>Controller statement</label><textarea id="f-narrative" placeholder="Describe the sequence of events, relevant clearances, readbacks, aircraft actions, traffic considerations, and subsequent communications.">${esc(d.atcReport.narrative)}</textarea></div><div class="field full"><label>Evidence URL</label><input id="f-evidence" value="${esc(d.atcReport.evidenceUrl)}" placeholder="Optional screenshot, video, or recording URL"><small>Links only for v1. Do not paste private or sensitive information.</small></div></div></div><div class="button-row"><button class="btn" id="back">BACK</button><button class="btn primary" id="next">REVIEW REPORT</button></div>`;document.getElementById('back').onclick=()=>{state.reportStep=2;renderFile()};document.getElementById('next').onclick=()=>{captureDynamic(d);d.atcReport.instruction=document.getElementById('f-instruction').value.trim();d.atcReport.observedAction=document.getElementById('f-action').value.trim();d.atcReport.narrative=document.getElementById('f-narrative').value.trim();d.atcReport.evidenceUrl=document.getElementById('f-evidence').value.trim();if(!d.atcReport.instruction||!d.atcReport.observedAction)return toast('ATC instruction and observed aircraft action are required.');state.reportStep=4;renderFile()}}
else{host.innerHTML=`<div class="form-section"><h3>Possible Pilot Deviation — Review</h3><div class="review-grid"><div class="review-item"><span>Callsign</span><strong>${esc(d.aircraft.callsign)}</strong></div><div class="review-item"><span>Pilot</span><strong>${esc(d.aircraft.playerName||'Not provided')}</strong></div><div class="review-item"><span>Aircraft</span><strong>${esc(d.aircraft.aircraftType)}</strong></div><div class="review-item"><span>Location</span><strong>${esc(d.incident.airport||d.incident.airspace||'Not specified')}</strong></div><div class="review-item"><span>Position</span><strong>${esc(d.incident.controllerPosition)}</strong></div><div class="review-item"><span>Time</span><strong>${esc(fmtTime(d.incident.occurredAt))}</strong></div><div class="review-item"><span>Incident</span><strong>${esc(d.incident.category)}</strong></div>${reviewDynamic(d)}</div><div class="review-block"><span>ATC CLEARANCE</span><p>${esc(d.atcReport.instruction)}</p></div><div class="review-block"><span>OBSERVED ACTION</span><p>${esc(d.atcReport.observedAction)}</p></div><div class="review-block"><span>CONTROLLER STATEMENT</span><p>${esc(d.atcReport.narrative||'No additional statement provided.')}</p></div></div><div class="callout warn" style="margin-bottom:15px">Issuing this report records a possible deviation for community review. It does not represent FAA action or real-world enforcement.</div><div class="button-row"><button class="btn" id="back">EDIT</button><button class="btn primary" id="issue">ISSUE PPD</button></div>`;document.getElementById('back').onclick=()=>{state.reportStep=3;renderFile()};document.getElementById('issue').onclick=issueReport}}
function dynamicFields(d){const c=d.incident.category;if(c==='Altitude Deviation')return`<div class="field"><label>Assigned altitude</label><input id="d-assigned-alt" inputmode="numeric" value="${esc(d.incident.assignedAltitude)}" placeholder="5000"></div><div class="field"><label>Observed altitude</label><input id="d-observed-alt" inputmode="numeric" value="${esc(d.incident.observedAltitude)}" placeholder="6200"></div>`;if(c==='Heading Deviation')return`<div class="field"><label>Assigned heading</label><input id="d-assigned-hdg" inputmode="numeric" value="${esc(d.incident.assignedHeading)}" placeholder="270"></div><div class="field"><label>Observed heading</label><input id="d-observed-hdg" inputmode="numeric" value="${esc(d.incident.observedHeading)}" placeholder="310"></div>`;if(c.includes('Runway')||c.includes('Takeoff')||c.includes('Landing'))return`<div class="field"><label>Assigned runway</label><input id="d-assigned-rwy" value="${esc(d.incident.assignedRunway)}" placeholder="27L"></div><div class="field"><label>Observed runway</label><input id="d-observed-rwy" value="${esc(d.incident.observedRunway)}" placeholder="27R"></div>`;return''}
function captureDynamic(d){const get=id=>document.getElementById(id)?.value.trim()||'';d.incident.assignedAltitude=get('d-assigned-alt');d.incident.observedAltitude=get('d-observed-alt');d.incident.assignedHeading=get('d-assigned-hdg');d.incident.observedHeading=get('d-observed-hdg');d.incident.assignedRunway=get('d-assigned-rwy');d.incident.observedRunway=get('d-observed-rwy')}
function reviewDynamic(d){if(d.incident.category==='Altitude Deviation'&&(d.incident.assignedAltitude||d.incident.observedAltitude)){const diff=(Number(d.incident.observedAltitude)||0)-(Number(d.incident.assignedAltitude)||0);return`<div class="review-item"><span>Assigned</span><strong>${esc(d.incident.assignedAltitude||'—')} FT</strong></div><div class="review-item"><span>Observed</span><strong>${esc(d.incident.observedAltitude||'—')} FT</strong></div><div class="review-item"><span>Difference</span><strong>${diff>=0?'+':''}${diff.toLocaleString()} FT</strong></div>`}if(d.incident.category==='Heading Deviation')return`<div class="review-item"><span>Assigned</span><strong>${esc(d.incident.assignedHeading||'—')}°</strong></div><div class="review-item"><span>Observed</span><strong>${esc(d.incident.observedHeading||'—')}°</strong></div>`;if(d.incident.assignedRunway||d.incident.observedRunway)return`<div class="review-item"><span>Assigned RWY</span><strong>${esc(d.incident.assignedRunway||'—')}</strong></div><div class="review-item"><span>Observed RWY</span><strong>${esc(d.incident.observedRunway||'—')}</strong></div>`;return''}
function toLocalInput(iso){const d=new Date(iso);const z=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
async function issueReport(){const btn=document.getElementById('issue');btn.disabled=true;btn.textContent='CREATING PPD…';let report;try{const body=await api('/api/reports/create',{method:'POST',body:JSON.stringify(state.draft)});report=body.report}catch(e){if(e.status===503&&e.body?.fallbackAllowed){report=localCreate(state.draft);toast('Google Sheets is not configured — created in local demo storage.')}else{btn.disabled=false;btn.textContent='ISSUE PPD';return toast('Could not create the report. Check server configuration.')}}state.issuedReport=report;renderIssued()}
function renderIssued(){const r=state.issuedReport;app.innerHTML=`${shellBanner()}<div class="issue-screen"><div class="issue-label">POSSIBLE PILOT DEVIATION</div><h2>${esc(r.aircraft.callsign)}</h2><div class="subtle mono">ADVISE WHEN READY TO COPY A NUMBER</div><div class="number-display">${esc(r.ppdNumber)}</div><div class="case-id">CASE ${esc(r.id)}</div><div class="phraseology"><strong>Suggested ATC24 wording</strong><br>“${esc(r.aircraft.callsign)}, possible pilot deviation. Advise when ready to copy a number.”<br><br>When ready: “Contact 24Pilot Deviation using number ${esc(r.ppdNumber)}.”</div><div class="button-row" style="justify-content:center"><button class="btn primary" id="copy-number">COPY NUMBER</button><button class="btn" id="copy-case">COPY CASE ID</button><button class="btn" id="return-aircraft">RETURN TO AIRCRAFT</button></div><div class="subtle" style="margin-top:22px">Unofficial ATC24 community process. This is not FAA phraseology or real-world enforcement.</div></div>`;document.getElementById('copy-number').onclick=()=>copy(r.ppdNumber,'PPD number copied.');document.getElementById('copy-case').onclick=()=>copy(r.id,'Case ID copied.');document.getElementById('return-aircraft').onclick=()=>{state.draft=freshDraft();state.reportStep=1;state.issuedReport=null;setRoute('aircraft')}}
async function copy(v,msg){try{await navigator.clipboard.writeText(v);toast(msg)}catch{toast(v)}}

function renderRespond(){const prefill=sessionStorage.getItem('24pd_lookup')||'';sessionStorage.removeItem('24pd_lookup');if(state.pilotStage==='lookup'){app.innerHTML=`${shellBanner()}<div class="section-head"><div><div class="eyebrow">Pilot response</div><h1>Locate Your PPD</h1><p>Enter the six-digit number given to you by ATC.</p></div></div><div class="found-card"><div class="field"><label>PPD NUMBER</label><input id="pilot-number" inputmode="numeric" value="${esc(prefill)}" placeholder="482731" style="font:600 30px var(--mono);letter-spacing:.12em;text-align:center"></div><div class="button-row" style="margin-top:15px"><button class="btn primary" id="pilot-lookup" style="width:100%">LOCATE REPORT</button></div><div class="subtle" style="margin-top:16px;text-align:center">Accepted: 482731 · 482-731 · 24PD-482731</div></div>`;document.getElementById('pilot-lookup').onclick=()=>lookupPilot(document.getElementById('pilot-number').value);document.getElementById('pilot-number').addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('pilot-lookup').click()});return}if(state.pilotStage==='found')return renderPilotFound();if(state.pilotStage==='contact')return renderContact();if(state.pilotStage==='form')return renderPilotForm();}
async function lookupPilot(value){const n=normalizeNumber(value);if(!n)return toast('Enter a valid six-digit PPD number.');const btn=document.getElementById('pilot-lookup');btn.disabled=true;btn.textContent='SEARCHING…';let report=null;try{const body=await api(`/api/reports/lookup?number=${encodeURIComponent(n)}`);report=body.report}catch(e){if(e.status===503&&e.body?.fallbackAllowed)report=localLookup(n);else if(e.status===404)return resetLookupButton(btn,'No active report was found for that number.');else return resetLookupButton(btn,'Unable to search reports right now.')}if(!report)return resetLookupButton(btn,'No local demo report was found for that number.');state.pilotCase=report;state.pilotStage='found';renderRespond()}
function resetLookupButton(btn,msg){btn.disabled=false;btn.textContent='LOCATE REPORT';toast(msg)}
function renderPilotFound(){const r=state.pilotCase;app.innerHTML=`${shellBanner()}<div class="found-card"><div class="eyebrow">Report located</div><h2>${esc(r.id)}</h2><div class="review-grid"><div class="review-item"><span>Callsign</span><strong>${esc(r.aircraft.callsign)}</strong></div><div class="review-item"><span>Aircraft</span><strong>${esc(r.aircraft.aircraftType)}</strong></div><div class="review-item"><span>Status</span><strong>${esc(r.status)}</strong></div><div class="review-item"><span>Incident</span><strong>${esc(incidentLabel(r.incident.category))}</strong></div><div class="review-item"><span>Location</span><strong>${esc(r.incident.airport||r.incident.airspace||'—')}</strong></div><div class="review-item"><span>Time</span><strong>${esc(fmtTime(r.incident.occurredAt||r.createdAt))}</strong></div></div><div class="callout" style="margin-top:18px">Only the incident information needed for your response is shown. Internal controller notes and moderation information are not exposed by the lookup number.</div><div class="button-row" style="margin-top:18px"><button class="btn" id="lookup-back">BACK</button><button class="btn primary" id="lookup-continue">CONTINUE</button></div></div>`;document.getElementById('lookup-back').onclick=()=>{state.pilotStage='lookup';state.pilotCase=null;renderRespond()};document.getElementById('lookup-continue').onclick=()=>{state.pilotStage='contact';renderRespond()}}
function renderContact(){const r=state.pilotCase;app.innerHTML=`${shellBanner()}<div class="contact-screen"><div class="eyebrow" style="justify-content:center">Online contact system</div><div class="contact-circle">24PD</div><h1 style="font-size:38px;margin:18px 0 8px">Case identified</h1><div class="number-display" style="font-size:50px;margin:20px 0">${esc(r.ppdNumber)}</div><p class="subtle" style="max-width:520px;margin:0 auto 24px;line-height:1.7">Verify that you are the pilot involved in this ATC24 incident, then continue to the structured response. This is an online workflow; no telephone call is being represented as completed.</p><button class="btn primary" id="begin-contact">I AM READY TO RESPOND</button></div>`;document.getElementById('begin-contact').onclick=()=>{state.pilotStage='form';renderRespond()}}
function renderPilotForm(){const r=state.pilotCase;const reported=r.reported||{instruction:r.atcReport?.instruction||'',observedAction:r.atcReport?.observedAction||''};app.innerHTML=`${shellBanner()}<div class="section-head"><div><div class="eyebrow">Pilot statement</div><h1>${esc(r.id)}</h1><p>Reported by ATC — not yet a final disposition.</p></div><span class="status-badge ${statusClass(r.status)}">${esc(r.status)}</span></div><div class="form-section"><h3>Reported incident</h3><div class="review-grid"><div class="review-item"><span>Callsign</span><strong>${esc(r.aircraft.callsign)}</strong></div><div class="review-item"><span>Aircraft</span><strong>${esc(r.aircraft.aircraftType)}</strong></div><div class="review-item"><span>Incident</span><strong>${esc(incidentLabel(r.incident.category))}</strong></div></div><div class="review-block"><span>REPORTED ATC INSTRUCTION</span><p>${esc(reported.instruction||'Not provided in the pilot-facing record.')}</p></div><div class="review-block"><span>REPORTED AIRCRAFT ACTION</span><p>${esc(reported.observedAction||'Not provided in the pilot-facing record.')}</p></div></div><div class="form-section"><h3>Your response</h3><div class="form-grid"><div class="field"><label>Roblox username *</label><input id="p-user" value="${esc(r.aircraft.playerName||'')}"></div><div class="field"><label>Were you operating this aircraft?</label><select id="p-operated"><option>Yes</option><option>No</option></select></div><div class="field full"><label>What instruction did you understand ATC to issue?</label><textarea id="p-understood"></textarea></div><div class="field full"><label>Describe what happened from your perspective *</label><textarea id="p-narrative"></textarea></div><div class="field"><label>Did you attempt to comply?</label><select id="p-comply"><option>Yes</option><option>No</option><option>Unsure</option></select></div><div class="field"><label>Emergency in progress?</label><select id="p-emergency"><option>No</option><option>Yes</option></select></div><div class="field"><label>Technical / game issue?</label><select id="p-tech"><option>No</option><option>Yes</option></select></div><div class="field"><label>Technical details</label><input id="p-tech-details" placeholder="Lag, disconnect, controls, simulator issue…"></div><div class="field full"><label>Additional information</label><textarea id="p-additional"></textarea></div></div></div><div class="button-row"><button class="btn" id="p-back">BACK</button><button class="btn primary" id="p-submit">SUBMIT RESPONSE</button></div>`;document.getElementById('p-back').onclick=()=>{state.pilotStage='found';renderRespond()};document.getElementById('p-submit').onclick=submitPilotResponse}
async function submitPilotResponse(){const response={pilotUsername:document.getElementById('p-user').value.trim(),operatedAircraft:document.getElementById('p-operated').value,understoodInstruction:document.getElementById('p-understood').value.trim(),narrative:document.getElementById('p-narrative').value.trim(),attemptedCompliance:document.getElementById('p-comply').value,emergency:document.getElementById('p-emergency').value,technicalIssue:document.getElementById('p-tech').value,technicalDetails:document.getElementById('p-tech-details').value.trim(),additionalInformation:document.getElementById('p-additional').value.trim()};if(!response.pilotUsername||!response.narrative)return toast('Roblox username and your incident description are required.');const btn=document.getElementById('p-submit');btn.disabled=true;btn.textContent='SUBMITTING…';try{await api('/api/reports/respond',{method:'POST',body:JSON.stringify({caseId:state.pilotCase.id,response})})}catch(e){if(e.status===503&&e.body?.fallbackAllowed){if(!localRespond(state.pilotCase.id,response)){btn.disabled=false;btn.textContent='SUBMIT RESPONSE';return toast('The local demo case could not be updated.')}}else{btn.disabled=false;btn.textContent='SUBMIT RESPONSE';return toast(e.status===409?'A pilot response has already been submitted.':'Unable to submit the response.')}}state.pilotCase.status='Pilot Responded';app.innerHTML=`${shellBanner()}<div class="issue-screen"><div class="issue-label">RESPONSE RECEIVED</div><div class="contact-circle" style="color:var(--green);border-color:rgba(85,214,158,.3)">✓</div><h2>Pilot response submitted</h2><p class="subtle">Your response has been associated with <span class="mono">${esc(state.pilotCase.id)}</span>.</p><div class="status-badge responded" style="margin:16px 0">PILOT RESPONDED</div><div class="button-row" style="justify-content:center;margin-top:24px"><button class="btn primary" id="response-home">RETURN HOME</button></div></div>`;document.getElementById('response-home').onclick=()=>{state.pilotCase=null;state.pilotStage='lookup';setRoute('home')}}

async function loadPublicReports(){try{const body=await api('/api/public/reports');state.publicReports=body.reports?.length?body.reports:DEMO_REPORTS.map(x=>({...x,demo:true}))}catch{state.publicReports=DEMO_REPORTS.map(x=>({...x,demo:true}))}}
function renderReports(){app.innerHTML=`${shellBanner()}<div class="section-head"><div><div class="eyebrow">Sanitized archive</div><h1>Public PPD Reports</h1><p>Public-facing summaries only. Private report fields are never displayed here automatically.</p></div></div><div class="filter-bar" style="grid-template-columns:2fr 1fr 1fr"><input id="report-search" placeholder="Search callsign, case, or location"><select id="report-incident"><option value="">All incidents</option>${[...new Set(state.publicReports.map(r=>r.incidentType))].map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="report-status"><option value="">All statuses</option>${[...new Set(state.publicReports.map(r=>r.status))].map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div id="reports-grid" class="reports-grid"></div>`;const draw=()=>{const q=document.getElementById('report-search').value.toLowerCase(),inc=document.getElementById('report-incident').value,st=document.getElementById('report-status').value;const rows=state.publicReports.filter(r=>(!q||`${r.id} ${r.callsign} ${r.location}`.toLowerCase().includes(q))&&(!inc||r.incidentType===inc)&&(!st||r.status===st));document.getElementById('reports-grid').innerHTML=rows.length?rows.map(r=>`<article class="report-card"><div class="case">${esc(r.id)} ${r.demo?'· DEMO':''}</div><h3>${esc(r.callsign)}</h3><p>${esc(r.aircraftType)}<br>${esc(r.incidentType)} · ${esc(r.location)}</p><div class="report-meta"><span class="status-badge ${statusClass(r.status)}">${esc(r.status)}</span><span class="subtle">${esc(r.date)}</span></div><div class="review-block" style="margin-top:14px"><span>SUMMARY</span><p>${esc(r.summary||'No public summary available.')}</p></div></article>`).join(''):`<div class="empty-state" style="grid-column:1/-1"><strong>No public reports found</strong>Try a different filter.</div>`};['report-search','report-incident','report-status'].forEach(id=>document.getElementById(id).addEventListener('input',draw));draw()}

mobileMenu.onclick=()=>{const open=nav.classList.toggle('open');mobileMenu.setAttribute('aria-expanded',String(open))};window.addEventListener('hashchange',render);window.addEventListener('keydown',e=>{if(e.key==='Escape')nav.classList.remove('open')});
(async function init(){await Promise.all([checkHealth(),loadPublicReports()]);render();refreshAircraft();setInterval(()=>{if(document.visibilityState==='visible')refreshAircraft()},5000)})();
